# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

frailty_est <- function(ftime, delta, trt, strata, trt_prob1, trt_prob0, censor_cov, surv_cov, censor_fit1, censor_fit0, beta_c1, beta_c0, surv_fit1, surv_fit0, beta_s1, beta_s0, e_time, RMST_cal = TRUE) {
    .Call(`_DRsurvCRT_frailty_est`, ftime, delta, trt, strata, trt_prob1, trt_prob0, censor_cov, surv_cov, censor_fit1, censor_fit0, beta_c1, beta_c0, surv_fit1, surv_fit0, beta_s1, beta_s0, e_time, RMST_cal)
}

marginal_est <- function(ftime, delta, trt, strata, trt_prob1, trt_prob0, censor_cov, surv_cov, censor_fit1, censor_fit0, surv_fit1, surv_fit0, e_time, RMST_cal = TRUE) {
    .Call(`_DRsurvCRT_marginal_est`, ftime, delta, trt, strata, trt_prob1, trt_prob0, censor_cov, surv_cov, censor_fit1, censor_fit0, surv_fit1, surv_fit0, e_time, RMST_cal)
}

